### ISSUE TITLE
Armored Elytra support

### ISSUE THREAD

**Issue by kossnikita** [Furgl/Hide-Armor#13]
With [Armored Elytra mod](https://www.curseforge.com/minecraft/mc-mods/armored-elytra) only the elytra is hidden, but not the chest
![2022-08-31_23 38 44](https://user-images.githubusercontent.com/39294101/187777871-3e52b14f-767e-4c27-8ee4-b83ef5d5385c.png)

**Comment by kossnikita** [comment]
https://github.com/Furgl/Hide-Armor/pull/12 doesn't affect

**Comment by Furgl** [comment]
Should be fixed in MC 1.19.4 with Hide Armor v2.6.0 (coming soon)
