### ISSUE TITLE
Crash with 1.19.3

### ISSUE THREAD

**Issue by SleepyCatten** [Furgl/Hide-Armor#16]
Hi,

Any attempt to load the plugin on 1.19.3 results in no server log, but solely the following error message.

![image](https://user-images.githubusercontent.com/92794563/209476853-4766d0aa-6aed-424e-960b-65bb42b57301.png)

Error
Game crashed

An unexpected error occurred and the game has crashed. We're sorry for
the inconvenience.
Exit Code: 1

**Comment by Furgl** [comment]
Should be fixed in MC 1.19.4 with Hide Armor v2.6.0 (coming soon)
