### ISSUE TITLE
[Fabric] Game Fails to Load, Mod Requests Java Version 17

### ISSUE THREAD

**Issue by Li-Liu** [Furgl/Hide-Armor#2]
### Issue Description:

After downloading and installing _Hide Armor_, the game crashes before reaching the main menu, shortly after launching, requesting _Java 17_.

I am not sure if this intended functionality or not, as **Java 17's** official release will come September 14th, 2021 and it remains in _early access_ for the time being.

### Step(s) to Reproduce:

**1.-** Download and Install Hide Armor
**2.-** Attempt to launch Minecraft with Java 16 or lower

### Environment:

- Java 16.0.1 OpenJ9 (AdoptOpenJDK)
- Minecraft v1.16.5
- Fabric 0.11.6
- Hide Armor 2.0 for 1.16.5

### Logs:

- [latest.log](https://github.com/Furgl/Hide-Armor/files/6815054/latest.log)
- [crash report.txt](https://github.com/Furgl/Hide-Armor/files/6815065/crash.report.txt)

### Screenshot(s):

N/A

### Additional Note(s):

N/A

**Comment by Furgl** [comment]
Thank you for letting me know - this is not intentional. I will get this fixed shortly.

**Comment by Furgl** [comment]
Fixed with v2.1 - https://www.curseforge.com/minecraft/mc-mods/hide-armor/files/3388636
