### ISSUE TITLE
Hide Armor Mod doesn't work with Wildfire's Female Gender Mod

### ISSUE THREAD

**Issue by WandingTraders** [Furgl/Hide-Armor#4]
Please fix this bug so when the chest plate is hidden its not showing the breast part of the armor. 
If this issue needs to be fixed by the Wildfire's Female Gender Mod maker, please tell me to reach out to them
I've got a link to my youtube video that shows the problem with this
Thanks
- Wandering

https://youtu.be/NVoEYXZP_W8

**Comment by Furgl** [comment]
Should be fixed in MC 1.19.4 with Hide Armor v2.6.0 (coming soon)
