### ISSUE TITLE
I have same problem

### ISSUE THREAD

**Issue by surfishs** [Furgl/Hide-Armor#6]
Please fix this bug so when the chest plate is hidden its not showing the breast part of the armor.
If this issue needs to be fixed by the Wildfire's Female Gender Mod maker, please tell me to reach out to them
I've got a link to my youtube video that shows the problem with this
Thanks

**Comment by Furgl** [comment]
Should be fixed in MC 1.19.4 with Hide Armor v2.6.0 (coming soon)
