### ISSUE TITLE
Can it be set to display Elytra separately?

### ISSUE THREAD

**Issue by zChenX1** [Furgl/Hide-Armor#7]
Can it be set to display Elytra separately?
I hope to be able to customize the location of the GUI, because it will be blocked by the potion BUFF
I really like your mod, I think it would be more complete if so

**Comment by dMoonShadowElf** [comment]
I agree i use it on a origins server and i want elytra's to show but not armor

**Comment by Furgl** [comment]
Support for hiding Elytra and pushing over potion effects in the GUI is added in v2.6.0 (coming soon)
