### ISSUE TITLE
Potion Effect overwrites the ArmorHUD

### ISSUE THREAD

**Issue by Scarlaid** [Furgl/Hide-Armor#9]
Apparently the potion effect HUD is more prior than the Hide Amor HUD
Would be nice if the Hide Armor HUD prior is higher since it's togglable
![image](https://user-images.githubusercontent.com/90851437/153807860-cb9816d1-5587-4a1c-83d0-58ff83cf9401.png)

**Comment by Furgl** [comment]
Should be fixed in MC 1.19.4 with Hide Armor v2.6.0 (coming soon)
